version: '3.5'

services:
   db:
      container_name: db
      ports:
         - '5432:5432'
      environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=admin
      image: postgres:14.3-alpine
